### ISSUE TITLE
SSL (https) on tegola

### ISSUE THREAD

**Issue by ocasti** [go-spatial/tegola#672] opened 2020-03-13 03:42 UTC
Tegola not work under ssl domain, the server rejected tiles if domin is https

**Comment by ARolek** [comment] 2020-03-13 17:50
@ocasti this is a dupe of #82. This has also been addressed in the v0.11.x branch but it's not yet in master. You can take a look at the PR here: https://github.com/go-spatial/tegola/pull/455

**Comment by ARolek** [comment] 2020-05-11 20:55
@ocasti this feature is now available in the most recent release of tegola. Please give it a run when you have a chance: https://github.com/go-spatial/tegola/releases

**Comment by ARolek** [comment] 2020-05-11 20:56
Oh and the associated docs (not yet on tegola.io): https://github.com/go-spatial/tegola/tree/master/server#config-properties

**Closed by ARolek** 2020-05-11 20:56 UTC
