### ISSUE TITLE
Caching not creating files  v0.19.0 is working. BUT master / v0.20.0 is NOT working.

### ISSUE THREAD

**Issue by spreeker** [go-spatial/tegola#997] opened 2024-07-03 10:12 UTC
tag v 20 out put run: 
`((v0.20.0))> ./tegola cache seed --log-level INFO --concurrency 3 --overwrite --min-zoom 13 --max-zoom 16 --config /home/stephan/work/cdfopen/tegola-config/config_gasverbruik_2024_06.toml --bounds "3.011234,50.16669,7.64906,54.683876"`

`
2024-07-03 12:01:53 [INFO] config.go:406: loading local config (/home/stephan/work/cdfopen/tegola-config/config_gasverbruik_2024_06.toml)
2024-07-03 12:01:53 [INFO] providers.go:82: registering provider(type): cdf (mvt_postgis)
2024-07-03 12:01:53 [INFO] seed_purge.go:194: zoom list: [13 14 15 16]
2024-07-03 12:01:53 [INFO] worker.go:94: seeding map (kvenergie202406v1) tile (13/4096/4095) took: 5ms
2024-07-03 12:01:53 [INFO] cache.go:213: waiting for workers to finish up
2024-07-03 12:01:53 [INFO] worker.go:94: seeding map (kvenergie202406v1) tile (16/32768/32767) took: 1ms
2024-07-03 12:01:53 [INFO] worker.go:94: seeding map (kvenergie202406v1) tile (14/8192/8191) took: 14ms
2024-07-03 12:01:53 [INFO] worker.go:94: seeding map (kvenergie202406v1) tile (15/16384/16383) took: 15ms
2024-07-03 12:01:53 [INFO] cache.go:223: all workers are done
2024-07-03 12:01:53 [INFO] provider.go:289: cleaning up providers
2024-07-03 12:01:53 [INFO] postgis.go:1039: cleaning up postgis providers`
`

So like 5 tiles are generated and nothing else.

in v0.19.0:

all tiles are generated. So what changed?

**Comment by spreeker** [comment] 2024-07-03 10:43
after commit 64729d1f1a384262bce54d7183303f491f338cba  cache seed of files stopped working for me.

**Comment by iwpnd** [comment] 2024-07-03 11:51
if im reading this correctly it is because the seed function was changed to default to webmercator as of [this change](https://github.com/go-spatial/tegola/blob/c7296fdf0022cdd93629b6884465183930bf0e70/cmd/tegola/cmd/cache/seed_purge.go#L206) for whatever reason. so in your case its trying to determine the tiles on a 3857 grid but with 4326 input bounds.

**Comment by spreeker** [comment] 2024-07-03 12:23
I'm not allowed to give input bounds via the cli other then 4326 i think.

`/tegola cache seed --log-level INFO --overwrite --min-zoom 8 --max-zoom 13 --config /home/stephan/work/cdfopen/tegola-config/config_gasverbruik_2024_06.toml --bounds "293518.1886,6555239.5457,847533.7696,7136160.9607"`


**`invalid lng value(293518.1886) for bounds (293518.1886,6555239.5457,847533.7696,7136160.9607)`**

**Comment by iwpnd** [comment] 2024-07-03 13:01
oh right, the cli has validation. 🤔 

hm, i wanna get this confirmed by @ARolek or @gdey if my suspicion is correct.

**Comment by gdey** [comment] 2024-07-03 19:53
I'll take a look at this tomorrow.

**Comment by gdey** [comment] 2024-07-04 21:39
Okay, I was able to create a quick test case for this. I'm digging into it. I think you are correct @iwpnd . Need to dig into why we make such a change. Looks like most of the .20 issues are from the upgrade. I'll keep people posted as I find out more.

**Comment by ARolek** [comment] 2024-07-20 20:30
Note, @gdey is working on a fix in the geom/slippy package that should address this issue. A PR will be ready soon and then we can do some testing.

**Comment by gdey** [comment] 2024-07-24 07:03
Okay, I'm very close to having some fixes for this. Got the slippy tile to native working again. And Writing up some tests on tile families, which is how get the set of tiles to use for seed/purging.

**Comment by ARolek** [comment] 2024-08-15 18:41
This has been addressed in https://github.com/go-spatial/tegola/pull/1007 and will be included in the next release.

**Closed by ARolek** 2024-08-15 18:41 UTC
